Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Training.Controllers.Base;
using Training.Models.Database;

namespace Training.Controllers;

public class LoginController : AppController
{

    public LoginController(Database context) : base(context)
    {
    }

    public IActionResult Index()
    {
        if(HttpContext.Session.GetString("user_id") != null)
        {
            return Redirect("/Welcome");
        }
        return View();
    }

    [HttpPost]
    public IActionResult Index(string Username, string Password)
    {
       var user = _context.Users.SingleOrDefault(x => x.Username == Username);

       if(user is null)
       {
           ViewBag.msg = "User not found, please register first";
           return View("Index");
       }

       bool isValidPassword = BCrypt.Net.BCrypt.Verify(Password, user.Password);

       if(isValidPassword) {
           HttpContext.Session.SetString("username", Username);
           HttpContext.Session.SetString("user_id", user.Id.ToString());
           HttpContext.Session.SetString("role_id", user.RoleId.ToString());
           return Redirect("/Welcome");
       }
       else
       {
           ViewBag.msg = "This data is not match with our credentials.";
           return View("Index");
       }
    }

    public IActionResult Logout()
    {
        HttpContext.Session.Remove("username");
        HttpContext.Session.Remove("user_id");
        HttpContext.Session.Remove("role_id");
        return Redirect("/");
    }
}

Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using Training.Controllers.Base;
using Training.Models.Database;

namespace Training.Controllers;

public class RoleController : AppController
{
    public RoleController(Database context) : base(context)
    {
    }

    public IActionResult Index()
    {
        IEnumerable<Role> roles = _context.Roles.ToList();
        return View(roles);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Role role)
    {
        if(ModelState.IsValid)
        {
            _context.Add(role);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        return View(role);
    }

    public IActionResult Edit(int? id)
    {
        if(id == null || id == 0)
        {
            return NotFound();
        }
        var role = _context.Roles.FirstOrDefault(r => r.Id == id);
        
        if(role is null)
        {
            return NotFound();
        }

        return View(role);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Role role)
    {
        if (ModelState.IsValid)
        {
            _context.Roles.Update(role);
            _context.SaveChanges();
            TempData["success"] = "Category Updated";
            return RedirectToAction("Index");
        }
        return View(role);
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Training</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Training.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Training</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if(HttpContextAccessor.HttpContext.Session.GetString("role_id") == "1")
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin Area
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-controller="Role" asp-action="Index">Roles</a></li>
                                    <li><a class="dropdown-item" asp-controller="UserManage" asp-action="Index">User Management</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <div class="d-flex">
                        <ul class="navbar-nav">
                            @if(HttpContextAccessor.HttpContext.Session.GetString("user_id") != null)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                                </li>
                            }   
                        </ul>
                           
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Training - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>